"""Fill the memo, evaluation page, and README measured blocks from harness JSON."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
LA = HERE / "label_agreement" / "results"
BR = HERE / "base_rate" / "results"
LK = HERE / "leakage_audit" / "results"


def _read(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))  # type: ignore[no-any-return]


def _md(path: Path) -> str:
    return path.read_text(encoding="utf-8").strip()


def render_memo() -> str:
    template = (HERE / "templates" / "research-memo.md").read_text(encoding="utf-8")
    la = _read(LA / "results.json")
    br = _read(BR / "results.json")
    lk = _read(LK / "results.json")
    la_md = _md(LA / "results.md")
    br_md = _md(BR / "results.md")
    lk_md = _md(LK / "results.md")
    la_table = "\n".join(line for line in la_md.splitlines() if line.startswith("|"))
    br_table = "\n".join(line for line in br_md.splitlines() if line.startswith("|"))
    lk_table = "\n".join(line for line in lk_md.splitlines() if line.startswith("|"))
    cam = br["labels"]["cam_icu"]
    filled = (
        template.replace("{{LA_N}}", str(la["n_included"]))
        .replace("{{LA_TABLE}}", la_table)
        .replace("{{LA_MEAN_KAPPA}}", f"{la['mean_kappa']:.3f}")
        .replace("{{LA_DECISION}}", str(la["decision"]))
        .replace("{{BR_N_RAW}}", str(br["n_raw"]))
        .replace("{{BR_N_INCLUDED}}", str(br["n_included"]))
        .replace("{{BR_N_EXCLUDED}}", str(br["n_excluded"]))
        .replace("{{BR_EXCLUDED_IDS}}", ", ".join(br["excluded_ids"]) or "(none)")
        .replace("{{BR_TABLE}}", br_table)
        .replace("{{BR_CAM_PREV}}", f"{cam['prevalence']:.3f}")
        .replace("{{LK_FEATURE}}", str(lk["offending_feature"]))
        .replace("{{LK_TIMESTAMP}}", str(lk["offending_timestamp"]))
        .replace("{{LK_SUBJECT}}", str(lk["offending_subject"]))
        .replace("{{LK_TABLE}}", lk_table)
        .replace("{{LK_P003}}", str(lk["notes_ablation_loses_p003"]).lower())
    )
    return filled


def render_eval() -> str:
    la = _md(LA / "results.md")
    br = _md(BR / "results.md")
    lk = _md(LK / "results.md")
    la_json = _read(LA / "results.json")
    return (
        "# Evaluation (Phase 0 baseline)\n\n"
        "Regenerated by `make eval` / `make research`. Model AUPRC, Brier, "
        "subgroup, and alert-burden numbers do not exist yet — those are "
        "declared below and measured in Phase 2/3. The label-agreement and "
        "base-rate tables are the baseline any later model must be reported "
        "against.\n\n"
        f"Mean pairwise label kappa: **{la_json['mean_kappa']:.3f}**. "
        f"Label choice dominates: **{la_json['label_choice_dominates']}**.\n\n"
        f"{la}\n\n{br}\n\n{lk}\n"
    )


def _replace_block(text: str, begin: str, end: str, body: str) -> str:
    start = text.index(begin) + len(begin)
    stop = text.index(end)
    return text[:start] + "\n\n" + body.strip() + "\n\n" + text[stop:]


def patch_readme() -> None:
    readme_path = ROOT / "README.md"
    text = readme_path.read_text(encoding="utf-8")
    la = _read(LA / "results.json")
    br = _read(BR / "results.json")
    lk = _read(LK / "results.json")
    cam = br["labels"]["cam_icu"]
    body = (
        "| Measurement | Value | n | Notes |\n"
        "| --- | --- | --- | --- |\n"
        f"| Mean pairwise label kappa | {la['mean_kappa']:.3f} | "
        f"{la['n_included']} | "
        f"{'Label choice dominates' if la['label_choice_dominates'] else 'Labels agree'} |\n"
        f"| CAM-ICU prevalence (included) | {cam['prevalence']:.3f} | "
        f"{br['n_included']} | Synthetic; not MIMIC-IV |\n"
        f"| Comfort-care excluded | {br['n_excluded']} | {br['n_raw']} | "
        f"{', '.join(br['excluded_ids'])} |\n"
        f"| Leakage rejected | {lk['offending_feature']} @ {lk['offending_timestamp']} | "
        f"P005 | Non-zero exit if used |\n"
        "| AUPRC / Brier / alert-burden | Phase 2 | — | Declared, not measured |\n"
    )
    text = _replace_block(text, "<!-- EVAL_TABLE_BEGIN -->", "<!-- EVAL_TABLE_END -->", body)
    readme_path.write_text(text, encoding="utf-8")


def main() -> None:
    memo = render_memo()
    memo_path = ROOT / "docs" / "phase-0" / "research-memo.md"
    memo_path.parent.mkdir(parents=True, exist_ok=True)
    memo_path.write_text(memo, encoding="utf-8")
    (ROOT / "docs" / "EVALUATION.md").write_text(render_eval(), encoding="utf-8")
    if (ROOT / "README.md").exists():
        patch_readme()
    print("wrote docs/phase-0/research-memo.md, docs/EVALUATION.md, README results block")


if __name__ == "__main__":
    main()
